name: box2d_flame
version: 0.4.1
authors:
- Kevin Moore <kevmoo@google.com>
- Srdjan Mitrovic <srdjan@google.com>
- Filip Hracek <filiph@google.com>
description: A Dart 2D physics engine
homepage: https://github.com/google/box2d.dart
dependencies:
  vector_math: '>=2.0.0 <3.0.0'
transformers:
- $dart2js:
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
