name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - name: Check dart version
      run: dart --version
    - name: Get dependencies
      run: pub get
      working-directory: forge2d
    - name: Run linting
      run: ./scripts/lint.sh
      working-directory: forge2d
    - name: Run sanity check build
      run: ./scripts/build.sh
      working-directory: forge2d
