name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - working-directory: forge2d
      - run: dart --version
      - run: pub get
      - run: ./scripts/lint.sh
      - run: ./scripts/build.sh
